/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateResourceHistoryArgs } from "./CreateResourceHistoryArgs";
import { UpdateResourceHistoryArgs } from "./UpdateResourceHistoryArgs";
import { DeleteResourceHistoryArgs } from "./DeleteResourceHistoryArgs";
import { ResourceHistoryFindManyArgs } from "./ResourceHistoryFindManyArgs";
import { ResourceHistoryFindUniqueArgs } from "./ResourceHistoryFindUniqueArgs";
import { ResourceHistory } from "./ResourceHistory";
import { Resource } from "../../resource/base/Resource";
import { User } from "../../user/base/User";
import { ResourceHistoryService } from "../resourceHistory.service";

@graphql.Resolver(() => ResourceHistory)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ResourceHistoryResolverBase {
  constructor(
    protected readonly service: ResourceHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ResourceHistory",
    action: "read",
    possession: "any",
  })
  async _resourceHistoriesMeta(
    @graphql.Args() args: ResourceHistoryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [ResourceHistory])
  @nestAccessControl.UseRoles({
    resource: "ResourceHistory",
    action: "read",
    possession: "any",
  })
  async resourceHistories(
    @graphql.Args() args: ResourceHistoryFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ResourceHistory[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "ResourceHistory",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => ResourceHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ResourceHistory",
    action: "read",
    possession: "own",
  })
  async resourceHistory(
    @graphql.Args() args: ResourceHistoryFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ResourceHistory | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "ResourceHistory",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => ResourceHistory)
  @nestAccessControl.UseRoles({
    resource: "ResourceHistory",
    action: "create",
    possession: "any",
  })
  async createResourceHistory(
    @graphql.Args() args: CreateResourceHistoryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ResourceHistory> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "ResourceHistory",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ResourceHistory"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        sourceID: {
          connect: args.data.sourceID,
        },

        userID: args.data.userID
          ? {
              connect: args.data.userID,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => ResourceHistory)
  @nestAccessControl.UseRoles({
    resource: "ResourceHistory",
    action: "update",
    possession: "any",
  })
  async updateResourceHistory(
    @graphql.Args() args: UpdateResourceHistoryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ResourceHistory | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "ResourceHistory",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ResourceHistory"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          sourceID: {
            connect: args.data.sourceID,
          },

          userID: args.data.userID
            ? {
                connect: args.data.userID,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ResourceHistory)
  @nestAccessControl.UseRoles({
    resource: "ResourceHistory",
    action: "delete",
    possession: "any",
  })
  async deleteResourceHistory(
    @graphql.Args() args: DeleteResourceHistoryArgs
  ): Promise<ResourceHistory | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Resource, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ResourceHistory",
    action: "read",
    possession: "any",
  })
  async sourceId(
    @graphql.Parent() parent: ResourceHistory,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Resource | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Resource",
    });
    const result = await this.service.getSourceId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ResourceHistory",
    action: "read",
    possession: "any",
  })
  async userId(
    @graphql.Parent() parent: ResourceHistory,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUserId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
