/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateCurrentSourceArgs } from "./CreateCurrentSourceArgs";
import { UpdateCurrentSourceArgs } from "./UpdateCurrentSourceArgs";
import { DeleteCurrentSourceArgs } from "./DeleteCurrentSourceArgs";
import { CurrentSourceFindManyArgs } from "./CurrentSourceFindManyArgs";
import { CurrentSourceFindUniqueArgs } from "./CurrentSourceFindUniqueArgs";
import { CurrentSource } from "./CurrentSource";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { CurrentSourceService } from "../currentSource.service";

@graphql.Resolver(() => CurrentSource)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CurrentSourceResolverBase {
  constructor(
    protected readonly service: CurrentSourceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CurrentSource",
    action: "read",
    possession: "any",
  })
  async _currentSourcesMeta(
    @graphql.Args() args: CurrentSourceFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [CurrentSource])
  @nestAccessControl.UseRoles({
    resource: "CurrentSource",
    action: "read",
    possession: "any",
  })
  async currentSources(
    @graphql.Args() args: CurrentSourceFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CurrentSource[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "CurrentSource",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => CurrentSource, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CurrentSource",
    action: "read",
    possession: "own",
  })
  async currentSource(
    @graphql.Args() args: CurrentSourceFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CurrentSource | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "CurrentSource",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => CurrentSource)
  @nestAccessControl.UseRoles({
    resource: "CurrentSource",
    action: "create",
    possession: "any",
  })
  async createCurrentSource(
    @graphql.Args() args: CreateCurrentSourceArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CurrentSource> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "CurrentSource",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CurrentSource"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => CurrentSource)
  @nestAccessControl.UseRoles({
    resource: "CurrentSource",
    action: "update",
    possession: "any",
  })
  async updateCurrentSource(
    @graphql.Args() args: UpdateCurrentSourceArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CurrentSource | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "CurrentSource",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CurrentSource"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CurrentSource)
  @nestAccessControl.UseRoles({
    resource: "CurrentSource",
    action: "delete",
    possession: "any",
  })
  async deleteCurrentSource(
    @graphql.Args() args: DeleteCurrentSourceArgs
  ): Promise<CurrentSource | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "CurrentSource",
    action: "read",
    possession: "any",
  })
  async userId(
    @graphql.Parent() parent: CurrentSource,
    @graphql.Args() args: UserFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const results = await this.service.findUserId(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
