/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateSourceDetailArgs } from "./CreateSourceDetailArgs";
import { UpdateSourceDetailArgs } from "./UpdateSourceDetailArgs";
import { DeleteSourceDetailArgs } from "./DeleteSourceDetailArgs";
import { SourceDetailFindManyArgs } from "./SourceDetailFindManyArgs";
import { SourceDetailFindUniqueArgs } from "./SourceDetailFindUniqueArgs";
import { SourceDetail } from "./SourceDetail";
import { SourceDetailService } from "../sourceDetail.service";

@graphql.Resolver(() => SourceDetail)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SourceDetailResolverBase {
  constructor(
    protected readonly service: SourceDetailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SourceDetail",
    action: "read",
    possession: "any",
  })
  async _sourceDetailsMeta(
    @graphql.Args() args: SourceDetailFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [SourceDetail])
  @nestAccessControl.UseRoles({
    resource: "SourceDetail",
    action: "read",
    possession: "any",
  })
  async sourceDetails(
    @graphql.Args() args: SourceDetailFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SourceDetail[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "SourceDetail",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => SourceDetail, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SourceDetail",
    action: "read",
    possession: "own",
  })
  async sourceDetail(
    @graphql.Args() args: SourceDetailFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SourceDetail | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "SourceDetail",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => SourceDetail)
  @nestAccessControl.UseRoles({
    resource: "SourceDetail",
    action: "create",
    possession: "any",
  })
  async createSourceDetail(
    @graphql.Args() args: CreateSourceDetailArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SourceDetail> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "SourceDetail",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SourceDetail"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => SourceDetail)
  @nestAccessControl.UseRoles({
    resource: "SourceDetail",
    action: "update",
    possession: "any",
  })
  async updateSourceDetail(
    @graphql.Args() args: UpdateSourceDetailArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SourceDetail | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "SourceDetail",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SourceDetail"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SourceDetail)
  @nestAccessControl.UseRoles({
    resource: "SourceDetail",
    action: "delete",
    possession: "any",
  })
  async deleteSourceDetail(
    @graphql.Args() args: DeleteSourceDetailArgs
  ): Promise<SourceDetail | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
