/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateResourceSuggestionArgs } from "./CreateResourceSuggestionArgs";
import { UpdateResourceSuggestionArgs } from "./UpdateResourceSuggestionArgs";
import { DeleteResourceSuggestionArgs } from "./DeleteResourceSuggestionArgs";
import { ResourceSuggestionFindManyArgs } from "./ResourceSuggestionFindManyArgs";
import { ResourceSuggestionFindUniqueArgs } from "./ResourceSuggestionFindUniqueArgs";
import { ResourceSuggestion } from "./ResourceSuggestion";
import { Resource } from "../../resource/base/Resource";
import { User } from "../../user/base/User";
import { ResourceSuggestionService } from "../resourceSuggestion.service";

@graphql.Resolver(() => ResourceSuggestion)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ResourceSuggestionResolverBase {
  constructor(
    protected readonly service: ResourceSuggestionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ResourceSuggestion",
    action: "read",
    possession: "any",
  })
  async _resourceSuggestionsMeta(
    @graphql.Args() args: ResourceSuggestionFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [ResourceSuggestion])
  @nestAccessControl.UseRoles({
    resource: "ResourceSuggestion",
    action: "read",
    possession: "any",
  })
  async resourceSuggestions(
    @graphql.Args() args: ResourceSuggestionFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ResourceSuggestion[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "ResourceSuggestion",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => ResourceSuggestion, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ResourceSuggestion",
    action: "read",
    possession: "own",
  })
  async resourceSuggestion(
    @graphql.Args() args: ResourceSuggestionFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ResourceSuggestion | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "ResourceSuggestion",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => ResourceSuggestion)
  @nestAccessControl.UseRoles({
    resource: "ResourceSuggestion",
    action: "create",
    possession: "any",
  })
  async createResourceSuggestion(
    @graphql.Args() args: CreateResourceSuggestionArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ResourceSuggestion> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "ResourceSuggestion",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ResourceSuggestion"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        ResourceID: args.data.ResourceID
          ? {
              connect: args.data.ResourceID,
            }
          : undefined,

        userID: {
          connect: args.data.userID,
        },
      },
    });
  }

  @graphql.Mutation(() => ResourceSuggestion)
  @nestAccessControl.UseRoles({
    resource: "ResourceSuggestion",
    action: "update",
    possession: "any",
  })
  async updateResourceSuggestion(
    @graphql.Args() args: UpdateResourceSuggestionArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ResourceSuggestion | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "ResourceSuggestion",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ResourceSuggestion"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          ResourceID: args.data.ResourceID
            ? {
                connect: args.data.ResourceID,
              }
            : undefined,

          userID: {
            connect: args.data.userID,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ResourceSuggestion)
  @nestAccessControl.UseRoles({
    resource: "ResourceSuggestion",
    action: "delete",
    possession: "any",
  })
  async deleteResourceSuggestion(
    @graphql.Args() args: DeleteResourceSuggestionArgs
  ): Promise<ResourceSuggestion | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Resource, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ResourceSuggestion",
    action: "read",
    possession: "any",
  })
  async resourceId(
    @graphql.Parent() parent: ResourceSuggestion,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Resource | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Resource",
    });
    const result = await this.service.getResourceId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ResourceSuggestion",
    action: "read",
    possession: "any",
  })
  async userId(
    @graphql.Parent() parent: ResourceSuggestion,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUserId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
