/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateSynonymArgs } from "./CreateSynonymArgs";
import { UpdateSynonymArgs } from "./UpdateSynonymArgs";
import { DeleteSynonymArgs } from "./DeleteSynonymArgs";
import { SynonymFindManyArgs } from "./SynonymFindManyArgs";
import { SynonymFindUniqueArgs } from "./SynonymFindUniqueArgs";
import { Synonym } from "./Synonym";
import { Keyword } from "../../keyword/base/Keyword";
import { SynonymService } from "../synonym.service";

@graphql.Resolver(() => Synonym)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SynonymResolverBase {
  constructor(
    protected readonly service: SynonymService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Synonym",
    action: "read",
    possession: "any",
  })
  async _synonymsMeta(
    @graphql.Args() args: SynonymFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Synonym])
  @nestAccessControl.UseRoles({
    resource: "Synonym",
    action: "read",
    possession: "any",
  })
  async synonyms(
    @graphql.Args() args: SynonymFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Synonym[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Synonym",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Synonym, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Synonym",
    action: "read",
    possession: "own",
  })
  async synonym(
    @graphql.Args() args: SynonymFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Synonym | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Synonym",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Synonym)
  @nestAccessControl.UseRoles({
    resource: "Synonym",
    action: "create",
    possession: "any",
  })
  async createSynonym(
    @graphql.Args() args: CreateSynonymArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Synonym> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Synonym",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Synonym"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        keywordId: {
          connect: args.data.keywordId,
        },
      },
    });
  }

  @graphql.Mutation(() => Synonym)
  @nestAccessControl.UseRoles({
    resource: "Synonym",
    action: "update",
    possession: "any",
  })
  async updateSynonym(
    @graphql.Args() args: UpdateSynonymArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Synonym | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Synonym",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Synonym"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          keywordId: {
            connect: args.data.keywordId,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Synonym)
  @nestAccessControl.UseRoles({
    resource: "Synonym",
    action: "delete",
    possession: "any",
  })
  async deleteSynonym(
    @graphql.Args() args: DeleteSynonymArgs
  ): Promise<Synonym | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Keyword, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Synonym",
    action: "read",
    possession: "any",
  })
  async keywordId(
    @graphql.Parent() parent: Synonym,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Keyword | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Keyword",
    });
    const result = await this.service.getKeywordId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
