/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSON, IsOptional, IsString, ValidateNested } from "class-validator";
import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ResourceHistoryCreateNestedManyWithoutUsersInput } from "./ResourceHistoryCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { KeywordCreateNestedManyWithoutUsersInput } from "./KeywordCreateNestedManyWithoutUsersInput";
import { ResourceSuggestionCreateNestedManyWithoutUsersInput } from "./ResourceSuggestionCreateNestedManyWithoutUsersInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  calendar?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => ResourceHistoryCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ResourceHistoryCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ResourceHistoryCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  historyID?: ResourceHistoryCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => KeywordCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => KeywordCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => KeywordCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  interestID?: KeywordCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  profession!: string;

  @ApiProperty({
    required: true,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: false,
    type: () => ResourceSuggestionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ResourceSuggestionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ResourceSuggestionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  suggestionID?: ResourceSuggestionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}
export { UserCreateInput };
