/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { UserListRelationFilter } from "../../user/base/UserListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { KeywordListRelationFilter } from "./KeywordListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { KeywordWhereUniqueInput } from "./KeywordWhereUniqueInput";
import { ResourceListRelationFilter } from "../../resource/base/ResourceListRelationFilter";
@InputType()
class KeywordWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => UserListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserListRelationFilter)
  @IsOptional()
  @Field(() => UserListRelationFilter, {
    nullable: true,
  })
  interested?: UserListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  keyIndex?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => KeywordListRelationFilter,
  })
  @ValidateNested()
  @Type(() => KeywordListRelationFilter)
  @IsOptional()
  @Field(() => KeywordListRelationFilter, {
    nullable: true,
  })
  keywords?: KeywordListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => KeywordWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => KeywordWhereUniqueInput)
  @IsOptional()
  @Field(() => KeywordWhereUniqueInput, {
    nullable: true,
  })
  parentKeyword?: KeywordWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ResourceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ResourceListRelationFilter)
  @IsOptional()
  @Field(() => ResourceListRelationFilter, {
    nullable: true,
  })
  resources?: ResourceListRelationFilter;
}
export { KeywordWhereInput };
