/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { KeywordWhereUniqueInput } from "./KeywordWhereUniqueInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { KeywordUpdateManyWithoutKeywordsInput } from "./KeywordUpdateManyWithoutKeywordsInput";
import { ResourceUpdateManyWithoutKeywordsInput } from "./ResourceUpdateManyWithoutKeywordsInput";
import { SynonymUpdateManyWithoutKeywordsInput } from "./SynonymUpdateManyWithoutKeywordsInput";
import { UserUpdateManyWithoutKeywordsInput } from "./UserUpdateManyWithoutKeywordsInput";
@InputType()
class KeywordUpdateInput {
  @ApiProperty({
    required: false,
    type: () => KeywordWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => KeywordWhereUniqueInput)
  @IsOptional()
  @Field(() => KeywordWhereUniqueInput, {
    nullable: true,
  })
  childID?: KeywordWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => KeywordUpdateManyWithoutKeywordsInput,
  })
  @ValidateNested()
  @Type(() => KeywordUpdateManyWithoutKeywordsInput)
  @IsOptional()
  @Field(() => KeywordUpdateManyWithoutKeywordsInput, {
    nullable: true,
  })
  parentID?: KeywordUpdateManyWithoutKeywordsInput;

  @ApiProperty({
    required: false,
    type: () => ResourceUpdateManyWithoutKeywordsInput,
  })
  @ValidateNested()
  @Type(() => ResourceUpdateManyWithoutKeywordsInput)
  @IsOptional()
  @Field(() => ResourceUpdateManyWithoutKeywordsInput, {
    nullable: true,
  })
  resourceID?: ResourceUpdateManyWithoutKeywordsInput;

  @ApiProperty({
    required: false,
    type: () => SynonymUpdateManyWithoutKeywordsInput,
  })
  @ValidateNested()
  @Type(() => SynonymUpdateManyWithoutKeywordsInput)
  @IsOptional()
  @Field(() => SynonymUpdateManyWithoutKeywordsInput, {
    nullable: true,
  })
  synonymID?: SynonymUpdateManyWithoutKeywordsInput;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutKeywordsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutKeywordsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutKeywordsInput, {
    nullable: true,
  })
  userID?: UserUpdateManyWithoutKeywordsInput;
}
export { KeywordUpdateInput };
