/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { KeywordListRelationFilter } from "./KeywordListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { KeywordWhereUniqueInput } from "./KeywordWhereUniqueInput";
import { ResourceListRelationFilter } from "../../resource/base/ResourceListRelationFilter";
import { SynonymListRelationFilter } from "../../synonym/base/SynonymListRelationFilter";
import { UserListRelationFilter } from "../../user/base/UserListRelationFilter";
@InputType()
class KeywordWhereInput {
  @ApiProperty({
    required: false,
    type: () => KeywordListRelationFilter,
  })
  @ValidateNested()
  @Type(() => KeywordListRelationFilter)
  @IsOptional()
  @Field(() => KeywordListRelationFilter, {
    nullable: true,
  })
  childID?: KeywordListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => KeywordWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => KeywordWhereUniqueInput)
  @IsOptional()
  @Field(() => KeywordWhereUniqueInput, {
    nullable: true,
  })
  parentID?: KeywordWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ResourceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ResourceListRelationFilter)
  @IsOptional()
  @Field(() => ResourceListRelationFilter, {
    nullable: true,
  })
  resourceID?: ResourceListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SynonymListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SynonymListRelationFilter)
  @IsOptional()
  @Field(() => SynonymListRelationFilter, {
    nullable: true,
  })
  synonymID?: SynonymListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserListRelationFilter)
  @IsOptional()
  @Field(() => UserListRelationFilter, {
    nullable: true,
  })
  userID?: UserListRelationFilter;
}
export { KeywordWhereInput };
