/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { JsonFilter } from "../../util/JsonFilter";
import { ResourceHistoryListRelationFilter } from "../../resourceHistory/base/ResourceHistoryListRelationFilter";
import { KeywordListRelationFilter } from "../../keyword/base/KeywordListRelationFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { ResourceSuggestionListRelationFilter } from "../../resourceSuggestion/base/ResourceSuggestionListRelationFilter";
@InputType()
class ResourceWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  abstract?: StringFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  authorS?: JsonFilter;

  @ApiProperty({
    required: false,
    type: () => ResourceHistoryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ResourceHistoryListRelationFilter)
  @IsOptional()
  @Field(() => ResourceHistoryListRelationFilter, {
    nullable: true,
  })
  historyID?: ResourceHistoryListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => KeywordListRelationFilter,
  })
  @ValidateNested()
  @Type(() => KeywordListRelationFilter)
  @IsOptional()
  @Field(() => KeywordListRelationFilter, {
    nullable: true,
  })
  keywordID?: KeywordListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  link?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  relaseDate?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => ResourceSuggestionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ResourceSuggestionListRelationFilter)
  @IsOptional()
  @Field(() => ResourceSuggestionListRelationFilter, {
    nullable: true,
  })
  suggestionID?: ResourceSuggestionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  title?: StringFilter;
}
export { ResourceWhereInput };
